<a href="https://colab.research.google.com/github/SandraMorata/SandraMorata/blob/main/Tema_1_Ejercicios_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### 1. Crea una matriz 10 x 10 que contenga los 100 primeros cuadrados

In [ ]:
array = np.arange(1, 101)
matriz = array.reshape(10, 10)
np.square

In [ ]:
# @title
matriz = np.arange(1,101).reshape((10,10))
display(matriz)
matriz = (matriz ** 2)
display(matriz)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

### 2. Calcula la matriz transpuesta de la matriz anterior

In [ ]:
# @title
matriz_t = matriz.T
display(matriz_t)

array([[    1,   121,   441,   961,  1681,  2601,  3721,  5041,  6561,
         8281],
       [    4,   144,   484,  1024,  1764,  2704,  3844,  5184,  6724,
         8464],
       [    9,   169,   529,  1089,  1849,  2809,  3969,  5329,  6889,
         8649],
       [   16,   196,   576,  1156,  1936,  2916,  4096,  5476,  7056,
         8836],
       [   25,   225,   625,  1225,  2025,  3025,  4225,  5625,  7225,
         9025],
       [   36,   256,   676,  1296,  2116,  3136,  4356,  5776,  7396,
         9216],
       [   49,   289,   729,  1369,  2209,  3249,  4489,  5929,  7569,
         9409],
       [   64,   324,   784,  1444,  2304,  3364,  4624,  6084,  7744,
         9604],
       [   81,   361,   841,  1521,  2401,  3481,  4761,  6241,  7921,
         9801],
       [  100,   400,   900,  1600,  2500,  3600,  4900,  6400,  8100,
        10000]])

### 3. Matriz inversa
Fija la semilla de aleatoriedad a 0, y genera una matriz aleatoria de enteros del 0 al 10 de tamaño 5x5.
Después de esto, calcula la inversa de dicha matriz.

In [ ]:
# @title
np.random.seed(0)
matriz_random = np.random.randint(0, high=11, size=5*5, dtype=int).reshape((5,5))
matriz_random_inv = np.linalg.inv(matriz_random)

np.matmul(matriz_random, matriz_random_inv)

array([[ 1.00000000e+00, -1.52655666e-16, -2.77555756e-16,
         3.33066907e-16, -4.71844785e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16,
         0.00000000e+00,  1.11022302e-16],
       [ 3.33066907e-16, -2.49800181e-16,  1.00000000e+00,
         2.22044605e-16, -1.66533454e-16],
       [ 0.00000000e+00, -4.44089210e-16,  4.44089210e-16,
         1.00000000e+00,  4.44089210e-16],
       [ 1.66533454e-16, -1.80411242e-16,  2.77555756e-16,
        -7.77156117e-16,  1.00000000e+00]])

### 4. Multiplicación matricial
Ahora multiplica tu matriz aleatoria original por su inversa. El resultado... ¿Es una matriz especial?

PISTA: Números muy pequeños se pueden entender como que son 0.

In [ ]:
# @title
resultado = np.matmul(matriz_random, matriz_random_inv)
print(resultado) # Es la matriz Identidad

### 5. Distancia entre puntos
Una tarea muy habitual en machine learning es trabajar con distancias. Para aprovechar y comparar las bondades de NumPy, implementa una función que calcule la distancia euclídea (https://es.wikipedia.org/wiki/Distancia_euclidiana) de dos puntos de dos maneras:
- Usando listas y bucles.
- Usando NumPy.

Luego, compara el tiempo de ejecución para 10000 cálculos

In [ ]:
# @title
array_x1 = np.arange(1,10001)
array_x2 = np.arange(1,10001) * 2 + 1
array_y1 = np.arange(1,10001) * 3 - 1
array_y2 = np.arange(1,10001) - 1

lista_x1 = array_x1.tolist()
lista_x2 = array_x2.tolist()
lista_y1 = array_y1.tolist()
lista_y2 = array_y2.tolist()

In [ ]:
[i for i in range]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [ ]:
# @title
%%timeit

# Listas y bucles

def dist_euclidea(x1, y1, x2, y2):
  return ((((x2 - x1) ** 2) + ((y2 - y1) ** 2)) ** 0.5)

for i in range(len(array_x1)):
  calc = dist_euclidea(lista_x1[i], lista_y1[i], lista_x2[i], lista_y2[i])

10.6 ms ± 2.33 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# @title
%%timeit

def dist_euclidea_vectorial(x1, y1, x2, y2):
  return ((((x2 - x1) ** 2) + ((y2 - y1) ** 2)) ** 0.5)

calc = dist_euclidea_vectorial(array_x1, array_y1, array_x2, array_y2)

# La solución basada en NumPy es unas 30 veces más rápida

320 µs ± 57.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
11.5 * 1000

11500.0

In [ ]:
11500 / 336

34.226190476190474